spring.application.name=AWS Simple Backend

server.address=0.0.0.0
server.port=8080

management.endpoints.web.exposure.include=health,info

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
