name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  BACKEND_REPOSITORY: simple-backend
  NGINX_REPOSITORY: simple-nginx

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend Docker image
        run: docker build -t $BACKEND_REPOSITORY:latest .

      - name: Tag backend Docker image
        run: docker tag $BACKEND_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

      - name: Push backend Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

      - name: Build nginx Docker image
        run: docker build -t $NGINX_REPOSITORY:latest ./nginx

      - name: Tag nginx Docker image
        run: docker tag $NGINX_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$NGINX_REPOSITORY:latest

      - name: Push nginx Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$NGINX_REPOSITORY:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster default \
            --service simple-backend-service-0y9a421b \
            --force-new-deployment